language: generic 

sudo: required
services: 
    - docker 

before_install:
    - docker build -t somoracle/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true somoracle/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-801753271921"
  bucket_path: "docker-react"
  on: 
    branch: master 
    access_key_id:
      secure: "CLxPbx/dAD82fOmsde9WgeeRe1bLDJgPUVwEQkqORU/60TKcpAwEiHzK8HbWnpI7+xq1D6H/eXqSDZiFhBGEHRC4cC0O1PaUdqsQKQcpgf998Phkw4ekjmdJsfiOw1SqLuBNFKpc/yQO3PijUu+h0hCoLWr2zrdc5uRHGOQx2RKo8pLN13qDSnQc4xH2jCa//foXQhT9dwLzbFL99xdTcUsFHk1D/3/jP5GyApod1eM926l5QcoI5TbOwoZDnppy2ExB1zieKBRftevH5abCpkJV2m9VsyMDhwXaGuYom7biYujq6F2kLtHMo9R94bN4bAFG3Oymvw8xc64tNowaU0/56yx5g8bFCDISGloiCbm/I8a2pQUvsDJS6OGVCZFiP+Z2AjqzOIRtuPMDuVyY59i18bgdQWUKWRXvKQdP5ROCT3SY94SJAojfy1q7v/q3OlZNFwAiTZhpXCVFtLT/+sViSpP6g810dEJiNyR60r4edDgKyx3Wvt0hCy8BVv7bRXbvak7+mXeLpwLIhMdEZh5gc/p5ZEisFX8KmvFQqEU1C8HTfSh1p5cyzDaGRKnBC6c3pnUsfIXGJOQ7r6Hzac1Da53TnuwTJUl2IZEgTCD6HAqKxIlM8I1rULBma+WlDoITPIlQsrrHa7TShAjF0U1LKkavtKV04BcItwJkdfg="
    secret_access_key:
      secure: "POlCk408+jd31yjXCRuyuE/XVuGrAVNXtOdprHzbSuPhay1QOkwndtaOTO0qXOMj1VRaxfxElEwMLdGdMk4fmZ53WR/rit/zEDEzv6XBykHPmXqLZg+UE7elCzZe7biINDME5bzWcumwDP0a2eTHF8pyWd3IMi83Zcdfbrj6NRtjuN6nIIEaABRwW1onCctMaEDPHLOuKWuXLi2BUiy2GNik2kt/FA1WkdghuoqKq/L/Uu9oWBWm5TNz3YJCMO+yb6Ts0ZkpjHVzOvjvqe8Q7f8JRy6kaqJG1HRzUcJJs9BUx4UqGB2CG/jO2fqJI2Aw3c5vMb2wAqsMCquYdk+UDtW7Vxcd9hbPAz+h4EAsE1JVnOZA5fwFK8+Zha5kDP+0bvGFFlH7gviY0UG8zUfA3/4Wfao2/dMFsb2gngi75CvN/DdPn1rJLuZ90vZ1kw+MpS/s5UZdoeaIWhsPI/BifGH3jhTgL8QMVe90XUy7aYzNh4IOKLS2p2IXpnVLdhyK5ElcMa4VBUb3MIEkRxd1nof8X2aFr/9g5yhQfZaNXYyk1bwkromdqLKpEdbySfo05Sc+kFUGvjGdylcHbyyPZcEBRBMVgrJUBzVFH8FFyANf1A8FqEkwNx/9UySG0p7CokhJNZFfXAaH+ulcffLb6DKya92wCvAF5ntiqKLS3GI="
  
  
    